### ISSUE TITLE
Info on research nodes doesn't update

### ISSUE THREAD

**Issue by Eccomi21** [Nogg-aholic/MAMTips#1]
### **- Release Version:** 
Alpha 0.1.0
### **- Description:** 
When inside the MAM (lol) after researching a node, the info doesn't update/change to the info of the new node I select. This is fixed by either exiting and re-entering the MAM or by switching to a different tab on the left and switching back.
### **- Steps to Reproduce:**
1. Enter the MAM
2. Select a research node
3. Research the node (stay inside the MAM)
4. After research has concluded, try selecting a different node. Info will not be updated and stay on the node you researched
### **- Expected Result:**
Research node info updates when selected
### **Actual Result:**
Research node stays on previous node information when selected
### **Defect Severity:**
Low
### **Defect Priority:**
Low
### **Comment:**
I believe this to be only relevant for the first few nodes that take 3 seconds to research as you usually exit the MAM anyways to do other things while waiting

**Comment by budak7273** [comment]
Whoops, I forgot to close this issue when it was fixed in [v0.2.0](https://ficsit.app/mod/EPUmESEWaBCk4n/version/3M6TbHvSNtoWBJ/view)
