### ISSUE TITLE
SMM Error

### ISSUE THREAD

**Issue by Keirons13** [Nogg-aholic/MAMTips#2]
Hi, I've recently installed SMM for the first time and installed your M.A.M Enhancer mod, and it's throwing up a Damaged error for this mod could you please help and maybe look into it please?

The error says: 
This mod has been reported as Damaged on this game version: Clicking "Add Cost to To-Do list" will crash, otherwise the mod works.

Is this a cause for concern and if so is there a way for me to rectify it, I hope this isn't too much of an issue and I hope to hear back from you

**Comment by Somnioblivio** [comment]
Seconding this error, can confirm that when adding things to the to-do list from the mam GUI insta-gibs the client... immediate hard-crash.

Any ETA on a fix perchance?

**Comment by budak7273** [comment]
Learn more about SMM 'damaged' status here: https://docs.ficsit.app/satisfactory-modding/latest/faq.html#_do_mods_work_with_experimental

This was fixed in v 1.0.3 and is no longer a concern. Thank you reporting it here though.
