### ISSUE TITLE
Message on right of selected item is blocking my view.

### ISSUE THREAD

**Issue by JamieRCHI** [Nogg-aholic/MAMTips#3]
I have been using the mod for awhile, and I do like it, but the message that tells me to look to the right is just in the way. In some of the views it covers up what I am trying to see. A message in a readme that tells users to look to the right for more information is all that is really needed.

**Comment by budak7273** [comment]
Can you send some screenshots of what elements are being covered? I have code set up to move that popup out of the way, but it might not be triggering correctly.

I'll see if I can make it less wide as well.

**Comment by Th3Fanbus** [comment]
> Can you send some screenshots of what elements are being covered? I have code set up to move that popup out of the way, but it might not be triggering correctly.

I've seen the message that tells you to look to the right cover the stuff to the right.

> I'll see if I can make it less wide as well.

I've thought about making the message be a dismissable pop-up, so that one can hide it forever after reading it.

**Comment by budak7273** [comment]
> I've seen the message that tells you to look to the right cover the stuff to the right.

It's supposed to flip to the left side if it spawns at further than 40% of the screen width, from the left but I guess that's not working correctly any more.

> I've thought about making the message be a dismissable pop-up, so that one can hide it forever after reading it.

Should be possible to tie it to a config option yeah

**Comment by Th3Fanbus** [comment]
Having a picture for reference would be nice.

**Comment by budak7273** [comment]
Fixed in 1.6.0
